# Generated by Django 5.1.1 on 2024-09-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather_api', '0002_delete_weatherdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STAID', models.IntegerField()),
                ('SOUID', models.IntegerField()),
                ('DATE', models.CharField(max_length=200)),
                ('TG', models.FloatField()),
                ('Q_TG', models.IntegerField()),
            ],
            options={
                'db_table': 'weather_data',
            },
        ),
    ]
