# Generated by Django 5.1.1 on 2024-10-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STAID', models.IntegerField()),
                ('STANAME', models.CharField(max_length=250)),
                ('CN', models.CharField(max_length=250)),
                ('LAT', models.CharField(max_length=250)),
                ('LON', models.CharField(max_length=250)),
                ('HIGHT', models.IntegerField()),
            ],
            options={
                'db_table': 'available_stations',
            },
        ),
    ]
