# Generated by Django 5.1.1 on 2024-10-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0004_availablestations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablestations',
            old_name='HIGHT',
            new_name='HGHT',
        ),
    ]
